// Curated Interesting Bible Facts for Scriptura (Rotates daily)

export const BIBLE_FACTS = [
  "Alkitab ditulis selama periode sekitar 1.500 tahun oleh lebih dari 40 penulis berbeda dari berbagai latar belakang.",
  "Kitab Mazmur adalah kitab terpanjang di Alkitab, sedangkan kitab Yudas atau 2 Yohanes adalah salah satu yang terpendek.",
  "Kata 'Alkitab' berasal dari kata Yunani 'Ta Biblia' yang berarti 'buku-buku' atau 'perpustakaan kecil'.",
  "Matius, Markus, dan Lukas disebut sebagai 'Injil Sinoptik' karena mereka menceritakan kisah Yesus dari sudut pandang yang serupa.",
  "Perjanjian Lama awalnya sebagian besar ditulis dalam bahasa Ibrani, sedangkan Perjanjian Baru ditulis dalam bahasa Yunani Kuno (Koine).",
  "Kitab Ester dan Kidung Agung adalah dua kitab di Alkitab yang tidak secara eksplisit menyebutkan nama 'Allah' atau 'Tuhan'.",
  "Alkitab adalah buku terlaris sepanjang sejarah umat manusia, dengan perkiraan lebih dari 5 miliar salinan telah terjual.",
  "Pelangi pertama kali disebutkan dalam Kejadian 9 sebagai tanda perjanjian Allah dengan Nuh bahwa bumi tidak akan dilanda air bah lagi.",
  "Pasal terpendek di Alkitab adalah Mazmur 117 (hanya 2 ayat), sedangkan pasal terpanjang adalah Mazmur 119 (176 ayat).",
  "Matusalah adalah orang tertua yang dicatat di Alkitab, hidup hingga usia 969 tahun (Kejadian 5:27).",
  "Kitab Yesaya sering disebut sebagai 'Alkitab Mini' karena memiliki 66 pasal, sama dengan jumlah kitab dalam Alkitab (39 PL + 27 PB).",
  "Hampir semua penulis Perjanjian Baru adalah orang Yahudi, kecuali Lukas yang merupakan seorang tabib Yunani.",
  "Ayat terpendek dalam Alkitab terjemahan Inggris KJV adalah Yohanes 11:35 ('Jesus wept' / 'Yesus menangis').",
  "Dalam bahasa asli Alkitab, tidak ada pembagian pasal dan ayat. Pembagian pasal dibuat pada abad ke-13, dan ayat pada abad ke-16.",
  "Gundukan naskah kuno Alkitab tertua yang pernah ditemukan adalah Gulungan Laut Mati (Dead Sea Scrolls) di Qumran pada tahun 1947.",
  "Nama terpanjang di Alkitab adalah 'Mahersyalal-hasy-bas' yang terdapat di Yesaya 8:1.",
  "Domba adalah hewan yang paling sering disebutkan di seluruh Alkitab, melambangkan kesucian dan pengorbanan.",
  "Perjanjian Baru pertama kali dicetak menggunakan mesin cetak Gutenberg pada tahun 1450-an, memulai revolusi literasi dunia.",
  "Ada 150 Mazmur di Alkitab, terbagi menjadi 5 kumpulan buku utama yang mencerminkan 5 kitab Taurat.",
  "Kitab Wahyu adalah satu-satunya kitab di Alkitab yang menjanjikan berkat khusus bagi mereka yang membaca dan mendengarkannya.",
  "Kitab Ayub diyakini oleh banyak teolog sebagai kitab tertua yang ditulis secara kronologis di Alkitab.",
  "Bahasa Aram adalah bahasa sehari-hari yang digunakan Yesus dan para murid di Yudea abad pertama.",
  "Kitab Amsal memiliki 31 pasal, sangat cocok dibaca satu pasal setiap hari menyesuaikan jumlah hari dalam sebulan.",
  "Mukjizat pertama Yesus yang dicatat dalam Injil Yohanes adalah mengubah air menjadi anggur di pesta pernikahan di Kana.",
  "Raja Salomo menulis sebagian besar kitab Amsal, Pengkhotbah, dan Kidung Agung.",
  "Istilah 'Bilingual' di Scriptura membantu kita membandingkan terjemahan TB (Terjemahan Baru) dan EN (KJV/NIV) untuk studi kata mendalam.",
  "Gunung Ararat (tempat bahtera Nuh mendarat) terletak di perbatasan antara Turki, Armenia, dan Iran modern.",
  "Nama 'Petrus' berarti batu karang, nama yang diberikan Yesus kepada Simon anak Yunus.",
  "Kitab Kejadian menceritakan permulaan segalanya (penciptaan, dosa, bangsa), sementara Wahyu menceritakan akhir dan pemulihan segalanya.",
  "Rut dan Ester adalah dua kitab di Alkitab yang dinamai berdasarkan tokoh perempuan utama mereka.",
  "Membaca Alkitab secara konsisten selama 15 menit sehari dapat membantu Anda menyelesaikan seluruh Alkitab dalam waktu satu tahun!"
];
